version: '3.8'

services:
  file-inclusion-ctf:
    image: shazsyed/bazaar-file-inclusion-ctf:latest
    ports:
      - "8080:8080"  # Optional if you need direct access
    networks:
      - ctf-network

  lfi-lab-microservice:
    image: shazsyed/bazaar-lfi-lab-microservice:latest
    ports:
      - "8087:8087"  # Optional if you need direct access
    networks:
      - ctf-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - file-inclusion-ctf
      - lfi-lab-microservice
    networks:
      - ctf-network

networks:
  ctf-network:
    driver: bridge
